### ISSUE TITLE
급) 댓글 입력 오류

### ISSUE THREAD

**Issue by kagla** [gnuboard/g6#258]
그누보드5에서 사용하던 DB에 그누보드6 설치후 

글쓰기는 정상
댓글쓰기는 아래와 같은 오류가 발생합니다

![image](https://github.com/gnuboard/gnu6/assets/99459574/eab67e03-5098-4457-8319-4635a697c55c)

**Comment by Junanjunan** [comment]
2c334144709dd67cf0d4469b0ec2a14d3810d824
해당 오류 수정 커밋입니다

**Comment by KimTom89** [comment]
현재 정상적으로 동작하는지 테스트 완료했습니다.
