### ISSUE TITLE
버그 5개 제보

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#271]
1. 수정 / 삭제가 되지 않는 버그 - 댓글이 없음에도 댓글 있다고 안내됨

2. 포인트가 적립되지 않는 버그 - 설정이 안되었을 수 있으나, 아예 적립이 안됨

3. 임의적인 접근 - https://g6.demo.sir.kr/board/free/5   정상   [https://g6.demo.sir.kr/board/free/ㅇ](https://g6.demo.sir.kr/board/free/%E3%85%87)  이렇게 하면 json 에러 반출 alert 창이 안뜸

4. 정보수정에서 아이디를 수정할 수 있음 - 테스트로 수정 해봤지만, 실제로는 수정되진 않음 ... 

5. faq 페이지에 관리자 메뉴가 보임 톱니바퀴 - 물론 접근은 안됨

**Comment by KimTom89** [comment]
2번째 포인트 관련 건은 확인해보니 자유게시판의 포인트는 설정되어있지 않았습니다.
다른 게시판에서도 동일한 문제가 발생하신다면 제보 부탁드립니다. :)
