### ISSUE TITLE
로컬에서 설치시 https 때문에 설치를 못하시는 분들에게...

### ISSUE THREAD

**Issue by munggo** [gnuboard/g6#305]
로컬에서 설치 시 https 때문에 설치를 못하시는 분들이 계실 것 같습니다.

로컬 서버에 인증서를 설치하는 등 귀찮은 작업을 피하고자 단순히 443포트 번호를 8000 포트로 proxy 처리를 하면 쉽게 설치가 가능합니다.

Mac을 기준으로 설명드릴게요. 터미널을 띄우고 아래와 같이 입력하면 프록시가 시작 됩니다.

`$ npx local-ssl-proxy --source 443 --target 8000`

이후 설치 경로로 접속하시면 정상적으로 설치 화면이 뜨는 걸 확인할 수 있습니다.

https://127.0.0.1/install/

요 부분이 README.md 에 포함되면 좋을것 같아서 남겨 드려요.

**Comment by geonyeong** [comment]
윈도우에서는 어떻헤 하나요?

**Comment by KimTom89** [comment]
@munggo 
@geonyeong 
https 강제 리다이렉팅으로 인한 설치 페이지 접근 오류는 #312 에서 수정되었습니다. 감사합니다 :)
