### ISSUE TITLE
wrestInitialized 를 글쓰기 회원가입 등 입력페이지에서만 실행

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#340]
wrest.js 에서 아래와 같이 선언되어 있어 페이지 로드 시마다 wrestInitialized 함수가 실행됩니다.

```
// 폼필드 자동검사
$(document).ready(function(){
    // onload
    wrestInitialized();
});
```

유효성 검사가 필요 없는 페이지에서는 wrestInitialized 를 실행할 필요가 없기 때문에

- 게시판 글쓰기
- 회원가입

등 유효성 검사가 필요한 페이지에서만 실행되도록 할 필요가 있습니다.

참고) 전체 검색창은 `fsearchbox_submit` 으로 유효성 검사를 하고 있기 때문에 이 변경에 영향을 받지 않습니다.

**Comment by whitedot** [comment]
엄격한 유효성 검사가 필요한 항목을 선별하여 적용 처리가 필요합니다.
#397 사례 참고

**Comment by whitedot** [comment]
아웃로그인에서 회원아이디 유효성 검사를 사용하기 때문에 wrest.js 파일 호출 위치는 변경하지 않습니다.
