### ISSUE TITLE
WYSYWIG 에디터에서 작성한 대로 보이게 하기

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#354]
게시물 조회할 때 WYSYWIG 에디터에서 작성한 대로 보이도록 해야 합니다.

**Comment by whitedot** [comment]
@KimTom89 
https://github.com/gnuboard/g6/blob/843c0476f315141e1f9d9982c7a9ace8a4c26f87/templates/basic/board/basic/read_post.html#L147

에디터를 사용하는 경우 에디터 이름을 class로 추가 가능할까요?

예를 들어,

```
<div id="bo_v_con" class="plain"> <!-- 에디터를 사용하지 않을 때 -->
<div id="bo_v_con" class="ckeditor"> <!-- 에디터를 사용할 때 -->
```

에디터마다 이름을 어떻게 지정할 것인지 이슈가 파생될 수 있을 것 같습니다.

**Comment by whitedot** [comment]
> 에디터마다 이름을 어떻게 지정할 것인지 이슈가 파생될 수 있을 것 같습니다.

에디터 디렉토리명 표시를 그대로 따르면 될 것 같네요.

![image](https://github.com/gnuboard/g6/assets/1720041/5265f359-fef5-4821-8fab-b45601c2e725)

**Comment by whitedot** [comment]
@KimTom89 에디터 이름 우선순위는 기본 방식을 따르면 될 것 같습니다.

> 게시판 에디터 사용여부 > 게시판 환경설정:에디터 > 기본 환경설정:에디터

**Comment by whitedot** [comment]
작업순서

1. reset 에서 정의된 아래 코드를 제거하고, ul dl dt dd 요소마다 제거한 속성값을 부여한다.
```
ul, dl, dt, dd { margin:0; padding:0; list-style:none }
```
2. font-size 단위를 em > rem 으로 변경한다. #380 연계
3. ckeditor 글자 크기를 default.css 글자 크기와 동일하게 수정한다.

**Comment by whitedot** [comment]
게시판 읽기 영역에서는 article, section, nav, aside 태그를 사용하지 않습니다.
브라우저 에이전트 룰에 의해 스타일 간섭이 발생합니다.

**Comment by whitedot** [comment]
70549b10e62a5cfad1668980ee896e437921a9cb

**Comment by whitedot** [comment]
적응형 관련 추가 작업 남아있습니다.

**Comment by whitedot** [comment]
9b1e32138f8fc91c06c4db5632784289bebf3130
