### ISSUE TITLE
font-size 단위 em > rem

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#380]
`em` 은 계산하기 어렵습니다.
기본 테마에서 `rem` 을 사용합니다.

**Comment by whitedot** [comment]
1. html 을 아래와 같이 선언하고,
```
html {
    font-size:0.625%;
}
```
2. em, px 등 rem 이외의 단위를 모두 rem 으로 변환합니다.
https://www.toolo.kr/pxtoem/
3. 단 외부 라이브러리에 포함된 스타일시트는 다루지 않습니다.

**Comment by dungdang39** [comment]
html의 font-size를 0.625%로 설정하는이유
