### ISSUE TITLE
외부서버 80 포트 실행 추가 요청

### ISSUE THREAD

**Issue by tlsdlftn79** [gnuboard/g6#382]
# 외부서버 80 포트 실행
 uvicorn main:app --reload --host {서버IP} --port 80 
추가 해주세요

**Comment by kagla** [comment]
https://github.com/gnuboard/g6/pull/383#issuecomment-1907194916
답변 드렸습니다.

이번에 반영은 되지 않았지만 의견 주셔서 감사합니다.
