### ISSUE TITLE
게시물 제목에 특수문자를 넣으면 HTML 예약어로 표시되는 문제

### ISSUE THREAD

**Issue by kagla** [gnuboard/g6#390]
https://sir.kr/g6_bug/2

OS : Ubuntu 22.04.3 LTS (GNU/Linux 4.9.337-35 aarch64)

파이썬 버전 : 3.12.1

FastAPI 버전 : 0.109.0

 

상황 : 게시물 제목에 쌍따옴표(")와 같은 특수문자를 넣으면 HTML 예약어인 & quot; 와 같이 출력됨

접속 가능한 외부 URL : [제목 특수문자... > 질문답변 (busanteddybear.com)](https://busanteddybear.com/board/qa/1)

 

에러메세지 전체 : 해당사항 없음

**Comment by Junanjunan** [comment]
@kagla 
현재 XSS 공격 방지용 코드가 적용되어서 &, <, >, ", \ 는 escape 되어 있습니다.
