### ISSUE TITLE
관리자에서 회원 추가 시 가입일 오류

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#396]
![image](https://github.com/gnuboard/g6/assets/122967713/823dafb2-b274-49dd-862f-83d25e415dc9)

가입일이 01년 01월 01일로 기록되는 것 같습니다.

**Comment by whitedot** [comment]
재확인 결과 패치된 것으로 보입니다. 문제 재발견 시 다시 다루겠습니다.
