### ISSUE TITLE
회원아이디 영문자, 숫자 외 입력 가능

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#397]
![image](https://github.com/gnuboard/g6/assets/122967713/a0d41de7-db46-4134-8ea6-448dfc1f4d40)

회원아이디에 한글도 입력이 됩니다.
다른 문자(특수문자)는 테스트해 보지 않았습니다.

**Comment by whitedot** [comment]
https://github.com/gnuboard/g6/blob/88a92d04c0c59b631af5711cabf58061c857185f/templates/basic/member/register_form.html#L28-L32

아래와 같이 수정하면 front-end 에서 검증할 수 있겠으나 back-end 처리도 추가 필요할 것 같습니다.
```
(수정 전) class="frm_input` full_input required "
(수정 후) class="frm_input` full_input required alnum_"
```
