### ISSUE TITLE
관리자 화면에서 값이 비정상적으로 출력

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#402]
![image](https://github.com/gnuboard/g6/assets/155944061/7dc8dca6-8d92-402c-98d6-d81c8129de42)

포인트 전체가 1건인데 5건 목록?

총 회원수는 1명인데 신규는 5명?

**Comment by whitedot** [comment]
등록된 전체 레코드 n 건 중 5건을 표시한다는 뜻입니다.
n>=5 일 때는 자연스러운 표현이지만, n<5 일 때는 부자연스러울 수 있겠습니다.

@KimTom89

**Comment by KimTom89** [comment]
말씀하신 내용대로 개발되었지만 부자연스러운 경우가 있어서 수정했습니다.
- 기존 : 5건 고정 표시
- 수정 : 출력된 레코드 건 수 표시 (최대 5건)

@whitedot
@seiblog-nandsoft
