### ISSUE TITLE
슬릭 테마 css / font 누락 

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#403]
슬릭 테마 css 및 font 누락

templates\basic\static\js\slick

해당 경로에 빠져 있습니다.

[slick-theme_font.zip](https://github.com/gnuboard/g6/files/14061033/slick-theme_font.zip)

또한 

templates\basic\base_sub.html

에 추가 해주세요

`<link rel="stylesheet" href="{{ theme_asset(request, 'js/slick/slick-theme.css?ver=1.8.1') }}">`

**Comment by whitedot** [comment]
라이브러리 커스터마이징이 필요하신 경우에는 직접 추가하여 사용해 주세요.

**Comment by seiblog-nandsoft** [comment]
> 라이브러리 커스터마이징이 필요하신 경우에는 직접 추가하여 사용해 주세요.

>> 커스터마이징이 아니라, 기본 사용법에 테마가 빠져있습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/3de3099f-a05f-40da-86a1-9bb89988512a)

저걸 쓰지 않으면, 슬라이드 내 화살표나, dot가 정상적으로 동작하지 않습니다 ㅡ.ㅡ;;;;
