### ISSUE TITLE
관리자에서 이미지로 된 아이콘을 font-awesome 이용하고, font-awesome 을 공통 라이브러리 취급하기

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#404]
1. 관리자에서 이미지로 된 아이콘을 font-awesome 으로 변경합니다.
    - 변경한 이미지는 삭제합니다.
2. font-awesome 을 테마에 종속되게 하지 않고 공통 라이브러리로 취급합니다.
    - templates/basic/static/js 에서 static/js 로 이동합니다.
    - 관리자, 사용자 기본 테마(basic)에서 theme_asset 대신 /static/js 경로를 이용합니다.

**Comment by whitedot** [comment]
cc. @KimTom89
