### ISSUE TITLE
투표 의견 남길 시 500 에러

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#406]
![image](https://github.com/gnuboard/g6/assets/155944061/55ad06e9-bfa5-41f1-a6d6-e4b0841613c9)

끝

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
안녕하세요. 데모사이트에서만 발생되었던 오류로 현재 수정되었습니다. 
제보해주셔서 감사합니다 :) 👍
