### ISSUE TITLE
게시판 html + stylesheet 리팩토링

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#429]
basic, gallery, qa 각각 성격에 맞게 html + stylesheet 를 리팩토링 하고,
default.css, qa.css로 분리된 스타일시트를 default.css 하나로 합합니다.

#### 예시
- #bo_{type}_list.bo_list
- #bo_{type}_view.bo_view
- #bo_{type}_write.bo_write

**Comment by whitedot** [comment]
연관이슈 https://github.com/gnuboard/g6/issues/430

**Comment by whitedot** [comment]
https://github.com/gnuboard/g6/commit/f3599edba7a69cc0073fe5f5324108c48e2ca706
이 시점부터 basic 게시판에 반응형 스타일이 적용됩니다.

**Comment by whitedot** [comment]
사이드뷰 사용 시, 게시판 읽기 레이아웃 깨지고 있음
