### ISSUE TITLE
게시판, 내용관리 스타일시트 분리

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#430]
templates(theme) 단위로 구조가 설계되었으므로 관리자에서 스킨 설정 항목 대부분은

1. 제거를 하거나
2. 게시판의 경우 list, grid(gallery) 타입 중 선택할 수 있도록

변경이 필요합니다.

단, 사용성/배포성 측면에서 충분한 검토가 선행되어야 하겠습니다.

**Comment by whitedot** [comment]
@KimTom89 게시판, 내용은 통합한 CSS를 분리해서 적용하겠습니다.

1:1 문의는 스킨 사용 필요가 없는지 검토 부탁드립니다.

**Comment by whitedot** [comment]
스킨별로 스타일시트, JS를 관리할 수 있는 방법이 필요할 것 같습니다.
