### ISSUE TITLE
게시글 첨부 이미지 확대 보기 추가 필요

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#436]
첨부 이미지 확대 보기 추가가 필요합니다.

https://github.com/gnuboard/g6/blob/42c1db6b37e2edfbd50d560cf4fe62add33b17fb/templates/basic/board/basic/read_post.html#L579-L582

스크립트는 존재하나 실제 작동은 안됩니다.

**Comment by KimTom89** [comment]
첨부 이미지의 경로로 새 창(별도의 기능 없음)이 뜨도록 수정했습니다. 감사합니ㅏ :)
