### ISSUE TITLE
갤러리 글 쓰기 폼 CSS 이상

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#440]
![image](https://github.com/gnuboard/g6/assets/155944061/beae58eb-6332-45d7-b692-09082cda30ec)

**Comment by whitedot** [comment]
https://github.com/gnuboard/g6/issues/429

연계하여 확인 및 처리 예정입니다.

**Comment by whitedot** [comment]
https://github.com/gnuboard/g6/commit/82af08ab19a1b68935a329c414cef308c72c0abd

처리되었습니다. 다른 이상이 있으시다면 알려주세요. 감사합니다.
