### ISSUE TITLE
사용하지 않는 이미지 삭제

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#448]
1. 사용하지 않는 이미지를 삭제합니다.
2. 사용하는 이미지더라도 아래의 경우 대체하고 삭제합니다.
    - 사용하지 않는 코드/스타일시트에 연결된 경우
        - 스타일시트는 삭제
        - 코드는 리포팅만
    - font-awesome 등으로 대체 가능한 경우

### 이미지 목록
- g6/static/img/mobile
- g6/static/img/mobile/btn_close.png
- g6/static/img/mobile/gnb_bg.png
- g6/static/img/mobile/gnb_bg2.png
- g6/static/img/mobile/gnb_sch.png
- g6/static/img/mobile/icon_menu.png
- g6/static/img/mobile/icon_my.png
- g6/static/img/social
- g6/static/img/social/sns_fb_s.png
- g6/static/img/social/sns_gp_s.png
- g6/static/img/social/sns_kakao_s.png
- g6/static/img/social/sns_logo_not.png
- g6/static/img/social/sns_logo.png
- g6/static/img/social/sns_naver_s.png
- g6/static/img/social/sns_payco_s.png
- g6/static/img/social/sns_twitter_s.png
- g6/static/img/btn_end.gif
- g6/static/img/btn_first.gif
- g6/static/img/btn_idx_left.png
- g6/static/img/btn_idx_right.png
- g6/static/img/btn_next.gif
- g6/static/img/btn_prev.gif
- g6/static/img/btn_search.jpg
- g6/static/img/btn_top.gif
- g6/static/img/bullet.gif
- g6/static/img/captcha.png
- g6/static/img/captcha2.png
- g6/static/img/chk.png
- g6/static/img/close_btn.gif
- g6/static/img/close_btn.png
- g6/static/img/ft_logo.png
- g6/static/img/ft.png
- g6/static/img/gnb_bg.gif
- g6/static/img/gnb_bg00.gif
- g6/static/img/gnb_bg01.gif
- g6/static/img/gnb_bg2.gif
- g6/static/img/ico-default-naverpay.png
- g6/static/img/ico-mobile-applepay.png
- g6/static/img/ico-mobile-kakaopay.png
- g6/static/img/ico-mobile-naverpay.png
- g6/static/img/icon_reply.gif
- g6/static/img/icon_secret.gif
- g6/static/img/kakao.png
- g6/static/img/kpay.png
- g6/static/img/logo_gnuboard6.png
- g6/static/img/logo_new.png
- g6/static/img/logo_red.png
- g6/static/img/logo_white.png
- g6/static/img/logo.png
- g6/static/img/lpay_logo.png
- g6/static/img/m_logo.png
- g6/static/img/more-btn.gif
- g6/static/img/no_img.png
- g6/static/img/no_profile.gif
- g6/static/img/pay_icon1.png
- g6/static/img/pay_icon2.png
- g6/static/img/pay_icon3.png
- g6/static/img/pay_icon4.png
- g6/static/img/payco_logo.png
- g6/static/img/payco.png
- g6/static/img/paynow_logo.png
- g6/static/img/paynow.png
- g6/static/img/require.png
- g6/static/img/samsungpay.png
- g6/static/img/sch_btn.png
- g6/static/img/tnb_shop.jpg
- g6/static/img/ts01.gif
- g6/static/img/ts01.png
- g6/static/img/ts02.gif
- g6/static/img/ts02.png
- g6/static/img/ts03.gif
- g6/static/img/ts03.png
- g6/static/img/wrest.gif

**Comment by whitedot** [comment]
- SNS에서 사용
	- social/sns_fb_s.png
	- social/sns_gp_s.png
	- social/sns_kakao_s.png
	- social/sns_logo_not.png
	- social/sns_logo.png
	- social/sns_naver_s.png
	- social/sns_payco_s.png
	- social/sns_twitter_s.png
- 모바일에서 사용
	- mobile/gnb_bg.png
	- mobile/gnb_bg2.png
- 텍스트 사이즈에서 사용
	- ts01.png
	- ts02.png
	- ts03.png
- 필수입력에서 사용
	- require.png
- 회원 프로필에서 사용
	- no_profile.gif
- 최근게시물에서 사용
	- no_img.png
- base 에서 사용
	- logo_gnuboard6.png
	- logo.png
- admin/게시판에서 사용
	- icon_reply.gif
	- wrest.gif
- GNB에서 사용
	- gnb_bg2.gif
- 체크박스에서 사용
	- chk.png
- 페이징에서 사용
	- btn_end.gif
	- btn_first.gif
	- btn_next.gif
	- btn_prev.gif
- 캡챠
	- captcha2.png
- 게시판에서 사용
	- close_btn.png

**Comment by whitedot** [comment]
(삭제함) 페이징에서 사용
- btn_end.gif
- btn_first.gif
- btn_next.gif
- btn_prev.gif

**Comment by whitedot** [comment]
최소한(혹은 미처 확인하지 못한 일부)의 이미지만 남기고, 대부분의 이미지를 삭제하거나 대체했습니다.
