### ISSUE TITLE
[fix] 첨부이미지 없을 때 이미지 영역 빈공간처럼 보이는 현상 수정

### ISSUE THREAD

**Issue by supwayb** [gnuboard/g6#467]
![image](https://github.com/gnuboard/g6/assets/122967713/6344ac5a-24cf-4b0e-b36c-4b4b3bfa1a9b)

첨부이미지가 없을 때 썸네일 영역이 빈공간처럼 보이는 현상이 있습니다.

- 최신글에서 썸네일 이미지 호출할 때
- 갤러리 스킨을 이용하는 게시판에서 썸네일 이미지 호출할 때

**Comment by whitedot** [comment]
image container에 가상선택자를 이용하여 no image 표기하여 처리하겠습니다.
