### ISSUE TITLE
관리권한설정 > 관리권한추가 > 접근가능 메뉴가 순서대로 출력되었으면 합니다.

### ISSUE THREAD

**Issue by kagla** [gnuboard/g6#481]
![image](https://github.com/gnuboard/g6/assets/99459574/bc10c5ce-7690-4667-8ba5-0c726aa202dd)

**Comment by KimTom89** [comment]
@kagla
어떤 기준으로 정렬하면 될까요..?

**Comment by kagla** [comment]
> @kagla 어떤 기준으로 정렬하면 될까요..?

메뉴 번호로 정렬되면 좋겠네요.
