### ISSUE TITLE
에디터에서 사진 첨부시 URL 문제

### ISSUE THREAD

**Issue by twk1024** [gnuboard/g6#498]
OS : Raspberry Pi OS (Bookworm)
파이썬 버전 : 3.11

상황 :
1. 그누보드 초기 설치 후 로컬 환경(192.168.0.xx:8000)에서 몇몇 테스트 글을 작성하였습니다.
2. 이후 외부 도메인을 Apache2 Proxy를 통해 연결하였습니다
3. 도메인 연결 이후 해당 외부도메인으로 접속할 경우 사진 미리보기는 잘 보이나, 글 내부에서 사진이 표시되지 않습니다

- 접속한 주소는 외부 도메인이지만, 글 내부 사진의 링크가 192.168.0.xx:8000/data/... 으로 고정되어 있어서 외부에서 접속할 시 사진이 표시되지 않습니다.
- 일반 첨부파일로 첨부한 사진은 정상 표시됩니다.
- 관리자 페이지의 캐시 삭제 등 시도하였으나 변화가 없었습니다

![Screenshot_20240308-074417](https://github.com/gnuboard/g6/assets/42838268/94e13949-b2a9-41a3-b95e-5eb5e0ae6fb5)
![Screenshot_20240308-075421](https://github.com/gnuboard/g6/assets/42838268/e3c00205-43c6-44c6-9f95-8b1f73c51f3c)
![Screenshot_20240308-074503](https://github.com/gnuboard/g6/assets/42838268/0e57181d-9d35-46b7-a3a3-5c9ebedeb6a0)

**Comment by KimTom89** [comment]
글 내부의 이전 도메인으로 설정된 이미지 주소를 불러오려면, `wr_content` 컬럼의 데이터를 **직접 수정**해야 합니다. 
아래와 같은 쿼리문으로 수정이 가능하며, 쿼리문을 실행할 경우 데이터가 손상될 수 있으므로 테스트 후 사용하기 바랍니다. 

``` sql
UPDATE {{ 테이블 }}
SET wr_content = REPLACE(wr_content, 'src="{{ 이전 도메인 }}', 'src="{{ 새 도메인 }}')
WHERE wr_content LIKE '%src="{{ 이전 도메인 }}%' 
```

참고 : https://sir.kr/qa/369927

**Comment by twk1024** [comment]
해결법까지 자세히 알려주셔서 감사합니다!
