### ISSUE TITLE
임시저장 글 가져오기 비동작

### ISSUE THREAD

**Issue by Junanjunan** [gnuboard/g6#515]
글 작성시 임시저장 글 목록 버튼이 작동하지 않습니다.

버튼 클릭시 함수를 걸어놓은 id가 일치하지 않아서 동작하지 않는데 아래 사진과 같이 id가
btn_autosave_list, btn_autosave로 템플릿 마다 조금씩 다르게 설정되어 있어서 통일이 필요해 보입니다.

![image](https://github.com/gnuboard/g6/assets/73055499/e4efbcb6-6ef7-414e-bf65-8d41d26527e1)

**Comment by whitedot** [comment]
부트스트랩 테마가 추가되면서 리팩토링 된 부분이 롤백된 것으로 보입니다.

@dungdang39 #btn_autosave_list 로 통일해 주세요.

**Comment by ablokr** [comment]
![Screenshot_20240405_142330_Chrome](https://github.com/gnuboard/g6/assets/117660912/f372f133-f89c-4f50-8285-142dd70a7047)
저도 같은 이슈를 리포트 하러 왔어요

**Comment by ablokr** [comment]
![1712294684290](https://github.com/gnuboard/g6/assets/117660912/a2ac3ef5-246b-4a69-9625-fefa4dde2949)
저도 같은 이슈를 리포트하러 왔어요.
