### ISSUE TITLE
현재 접속자 카운트 안맞습니다.

### ISSUE THREAD

**Issue by xperia-query** [gnuboard/g6#530]
![image](https://github.com/gnuboard/g6/assets/114769749/f2b3f16a-ac7b-409c-aea0-c0ff68da4644)
카운트는 4
현재접속자 목록은 33

데모사이트

**Comment by KimTom89** [comment]
@xperia-query 
데모사이트에 반영되기 전에 확인하신 것 같습니다. 
2024-06-04 13:55:43 시간 부로 데모사이트 반영 완료되었습니다. :)
