### ISSUE TITLE
비회원 글 쓰기 시 

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#536]
![image](https://github.com/gnuboard/g6/assets/155944061/cde3fdb5-a513-4da9-96d2-cf97cd79003d)

비회원이라면 비밀번호의 INPUT 을 required 걸어두시는게 좋을 것 같습니다.

그냥 소위 생까고 글 등록하면 비밀번호를 입력하라고 안내창이 뜨는데

글 쓰는 페이지 자체내에서 먼저 제어 하는 게 ....라는 생각도 드네요 (참고로 댓글에는 표시되어있음)
![image](https://github.com/gnuboard/g6/assets/155944061/03c0da72-e833-4aaf-97fe-9fb811fa0664)

또한 비밀번호는 최소 비밀번호를 제어하는게 좋지 않을까? 라는 생각도 한번 듭니다

1 입력해도 등록이 되네요

**Comment by Junanjunan** [comment]
비회원 글쓰기 시에 비밀번호 입력받는 커밋이 master 브랜치에 업데이트가 되어 있습니다.
master branch 업데이트 사항을 받아 보시면 될 것 같습니다. (아래 링크는 해당 부분 수정 커밋입니다.)
https://github.com/gnuboard/g6/commit/2f57144683633ac46bb909df4676caa5bbb6cebc

**Comment by seiblog-nandsoft** [comment]
> 비회원 글쓰기 시에 비밀번호 입력받는 커밋이 master 브랜치에 업데이트가 되어 있습니다. master branch 업데이트 사항을 받아 보시면 될 것 같습니다. (아래 링크는 해당 부분 수정 커밋입니다.) [2f57144](https://github.com/gnuboard/g6/commit/2f57144683633ac46bb909df4676caa5bbb6cebc)

그럼 파일 압축이 잘못된 것 같네요

https://sir.kr/g6_tags/43

여기에서 6.0.1 버전 설치했거든요.. 위 커밋 보면 6.0.1 버전에 포함된 내용인데 없는거 보니 누락된 것으로 보입니다.

확인 부탁드려요^^

![image](https://github.com/gnuboard/g6/assets/155944061/3a7a155d-e20e-496b-a16e-1dcba3f28722)

**Comment by Junanjunan** [comment]
@seiblog-nandsoft 
올려주신 링크를 통해 다운로드 후 내부 코드가 반영되어 있는지 찾아보니 반영이 되어있습니다.
혹시 캐시나, 다른 커밋 내역의 코드로 서버를 실행 하신 건 아닌지 한번 확인 부탁드립니다.
