### ISSUE TITLE
게시글 불러오기 / 개별 게시글에서 추천/비추천 누락

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#537]
![image](https://github.com/gnuboard/g6/assets/155944061/c7024054-19f5-414d-a839-10573fdead05)

![image](https://github.com/gnuboard/g6/assets/155944061/e0c0f618-7e13-4ea4-a121-6bfb3851dadb)

api를 하나씩 적용해보고 있는데 ...없는것 발견했습니다.

건의: comments 배열값을 반환하기는 하지만, 코멘트의 개수를 바로 반환 해주셨으면 좋겠습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/0311854b-7c87-4b69-ab4c-0f2f12968b94)

이렇게 직접 comments.length 로 찍어서 사용은 하고 있다면, 실제 개수를 반환해주시면 더 좋을 듯 합니다.

**Comment by Junanjunan** [comment]
@seiblog-nandsoft 
1. 추천/비추천 누락 건
  - 말씀 주신 추천/비추천에 대해서 현재 별도의 API로 요청할 수 있습니다. 
    해당 API는 스웨거의 좋아요/싫어요 탭에서 확인이 가능하십니다.
  - 개별 게시글 요청시 좋아요/싫어요 수를 받을 수 있도록 API에 포함 시킬지 여부는
     내부 논의를 거쳐서 반영 여부를 결정 하도록 하겠습니다.
2. comment 개수에 관한 건
  - wr_comment 값을 이용하실 수 있습니다.

**Comment by seiblog-nandsoft** [comment]
> @seiblog-nandsoft
> 
> 1. 추천/비추천 누락 건
> 
> * 말씀 주신 추천/비추천에 대해서 현재 별도의 API로 요청할 수 있습니다.
>   해당 API는 스웨거의 좋아요/싫어요 탭에서 확인이 가능하십니다.
> * 개별 게시글 요청시 좋아요/싫어요 수를 받을 수 있도록 API에 포함 시킬지 여부는
>   내부 논의를 거쳐서 반영 여부를 결정 하도록 하겠습니다.
> 
> 2. comment 개수에 관한 건
> 
> * wr_comment 값을 이용하실 수 있습니다.

wr_comment 가 카운트였군요 하나씩 테스트 하다보니 1이다 0이다만 확인했네요

고맙습니다. 

이것저것 좀 보고 계속 알려드릴께요
