### ISSUE TITLE
[rest_api] 추천/비추천 값 누락 및 등록 딜레이 미적용

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#539]
![image](https://github.com/gnuboard/g6/assets/155944061/bdaa59b2-9bef-43f2-badc-202cac70401d)

금일 오후에 글 남겼었는데, 스웨거에 있다고는 하나, 포스트 형식(추천/비추천 등록)만 있고 해당 카운트를 가져오는 겟 형식은 없습니다.

확인 부탁드립니다.

또한, 일단 테스트로 확인 된건, 게시글 등록 및 댓글 등록이지만.
![image](https://github.com/gnuboard/g6/assets/155944061/d24a1f22-4aa2-44a1-b63d-92f7c84ee171)
글쓰기 간격이 30초 아니 300초 아니 3000초를 하더라도,

POST로 API 호출하면, 제약 없이 등록이 가능합니다.
아래 영상 보면 비회원 기준으로 댓글 등록하는데도 막 등록됩니다. (관리자 로그인 아닌 상태임)

글 등록도 마찬가지입니다.

https://github.com/gnuboard/g6/assets/155944061/fc111467-0b7c-4773-a753-4d2207444b92

마지막으로 금일 오후에 남겼던 게시글 기준 리스트 형태 상태에서 여분 필드도 출력되지 않지만,

글 보기(단일 조회건)에서도 여분 필드가 나타나지 않습니다.

진짜 마지막으로 회원정보 출력 시 회원 정보 여분 필드도 출력 되지 않습니다.

http://127.0.0.1:8000/api/v1/members/{mb_id}

![image](https://github.com/gnuboard/g6/assets/155944061/44a847c4-b2a6-4628-b6f2-070c6f6148df)

**Comment by Junanjunan** [comment]
@seiblog-nandsoft 
게시글 여분 필드와 관련해서, 현재 api 응답시 보여줄 데이터를 pydantic을 통해서 필터링 하고 있습니다.
여분 필드 데이터를 함께 받으시도록 하려면,
```python
// api/v1/models/board.py
class ResponseWriteModel(BaseModel):
  ...
  wr_1: str
  wr_2: str
  ...
```
과 같은 방식으로 원하는 속성을 추가하실 수 있습니다.
여분 필드 외에 다른 항목도 데이터베이스에 존재하는 필드에 맞게 응답 데이터에 속성을 추가하실 수 있습니다.

멤버 정보 조회 여분 필드와 관련해서도
api/v1/models/member.py > MemberResponse에 원하시는 속성을 추가하여 사용하실 수 있습니다.
