### ISSUE TITLE
[python + rest_api] 스크랩 시 데이터가 비정상적으로 출력

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#545]
![image](https://github.com/gnuboard/g6/assets/155944061/322d7977-2c03-4cc0-bfa6-47b6fd2e04fc)

내용을 볼 수 없고 클릭도 되지 않습니다.

+ 

rest_api 에서 스크랩 추가 시 wr_id 가 필수로 되어있지만, 필수로 하지 않아도 등록 됩니다.

![image](https://github.com/gnuboard/g6/assets/155944061/083767a4-d295-4b7d-9e8f-377cb52a9d44)

{
"bo_table: "free"
}

만 작성해도 등록됩니다.

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
현재 해당 오류의 재현이 어려워 오류를 파악하기 어렵습니다. 
스크랩 추가 시 어떤 형식으로 요청하시는지 알려주신다면 감사하겠습니다 :) (URL, Parameter 등)

**Comment by humorous-app** [comment]
아 그게 아니라, 스크랩 하고 나서 내 스크랩 메뉴를 누르니깐 저렇게 나오더라구요^^;;

**Comment by humorous-app** [comment]
@KimTom89 다시 확인해보니, 기본 템플릿은 정상적인데 부트 스트랩 테마에서 발생하는 오류네요

부트스트랩 > 스크랩 메뉴

**Comment by seiblog-nandsoft** [comment]
@KimTom89 아 아이디가 왔다갔다 해서 죄송합니다 하핫,,ㅋㅋㅋ

네..문제가 없이 그냥 등록되요, 다만, 게시판이 주소에 있음에도 게시판은 써야 됩니다

글 넘버만 생략 해도 등록이 됩니다.

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
API 요청시 `wr_id`를 누락할 경우 제대로 된 요청이 실행되지 않아서 제대로 된 오류를 확인 할 수가 없었습니다.

- API 문서에서 요청 테스트
![swagger 스크랩 등록 wr_id 누락시 오류](https://github.com/gnuboard/g6/assets/57935683/a945b52d-8ffc-48eb-91c6-2cb2278e6dea)

- Postman에서 요청 테스트
![Postman 스크랩 등록 wr_id 누락시 오류](https://github.com/gnuboard/g6/assets/57935683/a7c2b825-22c9-41b0-a121-f67474f6b257)


개인적으론 본문(Request Body)에 `wr_content` 외에 **다른 매개변수를 추가**한 것이 아닌가 조심스레 예상해봅니다.

본문에서는 `api/v1/models/scrap.py > CreateScrap` 클래스에 선언된 **`wr_content` 외의 변수들은 입력 여부와 관계 없이 처리**됨을 알려드립니다.

그리고 말씀해주신 부트스트랩에서 제목이 누락되는 오류는 다음 패치때 적용하도록 하겠습니다.
![부트스트랩 테마_스크랩 목록 출력](https://github.com/gnuboard/g6/assets/57935683/106a0353-5e28-4e8a-ae1b-0e20665bfa36)

감사합니다 :)

**Comment by seiblog-nandsoft** [comment]
@KimTom89 저도 퇴근해야 되서 ㅋ 포스트맨 관련은 내일 다시 이슈로 등록 하겠습니다. 설명 + 영상 포함
