### ISSUE TITLE
[rest_api] 비밀번호 찾기 이메일 수신이 되질 않습니다.

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#551]
![image](https://github.com/gnuboard/g6/assets/155944061/09e846c9-2ac6-4820-b4a2-465e2348ec68)

재설정 안내까진 되지만, 실제 전송은 되지 않는데

혹시 저만 그런지 테스트 한번 가능하실까요 ?

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
현재 테스트 했을 때는 정상적으로 전송됨을 확인했습니다.
![postman](https://github.com/gnuboard/g6/assets/57935683/c805f5f5-b0f4-45c1-beb2-5a20940f6b8c)
![메일수신](https://github.com/gnuboard/g6/assets/57935683/99f1c1b0-7635-4c71-ae13-1a0e7295c4b0)


아래 `.env`파일의 코드를 참고하셔서 각 메일에 맞는 설정을 다시한번 확인해주시기 바랍니다.
감사합니다 :)

``` .env
# 메일 테스트시 보내는 사용자 이름 및 이메일 주소 반드시 넣어야 함 SMTP_USERNAME="username@domain.com"
# Gmail
# SMTP_SERVER="smtp.gmail.com"
# SMTP_PORT=587
# SMTP_USERNAME=""  # 이메일 주소
# SMTP_PASSWORD=""  # 2단계 인증(앱 비밀번호)

# 다음 메일
# SMTP_SERVER="smtp.daum.net"
# SMTP_PORT=465
# SMTP_USERNAME=""  # 계정 아이디
# SMTP_PASSWORD=""  # 비밀번호 or 2단계 인증(앱 비밀번호)

# 네이버 메일
# SMTP_SERVER="smtp.naver.com"
# SMTP_PORT=465
# SMTP_USERNAME=""  # 계정 아이디
# SMTP_PASSWORD=""  # 비밀번호 or 2단계 인증(앱 비밀번호)
```
