### ISSUE TITLE
[rest_api] 어색한 텍스트 수정 건의

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#555]
지금 확인 해본 건 2건인데

![image](https://github.com/gnuboard/g6/assets/155944061/74845296-15d7-4852-bbfb-bb418c4e32ac)
![image](https://github.com/gnuboard/g6/assets/155944061/a093e61b-429d-473a-94ea-cb2c0133039b)

쪽지 발송 / 및 회원 정보 검색 할 때 없는 아이디 출력 시

아이디 : XXXXXXXXXXXXXXXXXXXXXX 메세지 출력

그냥 메세지 출력하고 아이디는 생략하는게 어떨까? 싶습니다.

그러니깐 회원 정보가 존재하지 않거나 탈퇴/차단된 회원입니다. 라는 메세지만 출력해도 될 것 같습니다.

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
구분자(',')를 통해 여러 회원에게 한번에 쪽지를 전송할 경우
**어떤 아이디가 유효성 검사에 통과하지 못했는지 알려주기 위해서** 아이디를 출력해주고 있습니다.

의견주셔서 감사합니다 :)
