### ISSUE TITLE
그누보드6 설치 버그 및 DB_TABLE_PREFIX 미적용 이슈

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#558]
![Honeycam 2024-05-30 11-50-10](https://github.com/gnuboard/g6/assets/155944061/936eab77-93a3-4e02-ace6-0e717890c2f7)

1. 설치 시도 시 안전한 어쩌고 저쩌고 오류가 뜹니다.  

2. 움짤에 보시다 시피 분명히 g5 테이블뿐이고 입력 역시 g5 입력했음에도 강제로 g6 테이블이 생성 됩니다.

![image](https://github.com/gnuboard/g6/assets/155944061/e0bded92-d543-48ef-bbf3-d7430b423b37)

3.  env 파일에 DB_TABLE_PREFIX 가 G5인데도 G6만 인식합니다.

따라서 입력이 아무런 의미가 없는 것으로 보입니다 

------------------------------------

로컬에서 빈 test2 테이블에서 그누보드5 설치 없이 그누6를 g5 이름으로 설치 했습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/58af5ddf-f885-44df-b869-a4dff888741f)

일부는 g5로 (게시판 글)

나머지는 g6로 구현되고 있는게 맞는건가요 ?

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
1. 크롬 브라우저에서 http 요청을 차단하기 때문에 나타나는 현상인 것 같습니다.

2. 테이블 생성  시, 접두사를 인식하지 못하고 기본값인 'g6_'로 설정되는 오류입니다.  

테이블 생성 시, `models.py` 파일에 있는 `Base`의 메타데이터를 기반으로 테이블을 생성하게 됩니다.  
그런데 모델 클래스가 선언될 때, `DB_TABLE_PREFIX`의 값이 기본값인 '**g6_**'로 설정되기 때문에 문제가 발생합니다.   
이는 설치 전에는 `.env`파일이 없어 `DBConnect().table_prefix` 값이 제대로 설정되지 않았기 때문입니다.

``` python
# 아래 모델 클래스들은 서버 실행 시 `Base`에 메타데이터로 할당된다.
Base = declarative_base(cls=MySQLCharsetMixin)

DB_TABLE_PREFIX = DBConnect().table_prefix or "g6_"


class Config(Base):
    """
    환경설정 테이블
    """

    __tablename__ = DB_TABLE_PREFIX + "config"
...
```
해당 오류사항은 이후 패치에 수정해서 반영토록 하겠습니다

감사합니다

**Comment by seiblog-nandsoft** [comment]
@KimTom89 매번 힘들게 해서 죄송합니다!! 보다 완성된 그누6를 위해 노력하는거니 너무 미워하지 마세요^^
