### ISSUE TITLE
API 세팅 및 ENV 파일 내 내용 중복 ...

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#559]
ENV 파일의 내용

![image](https://github.com/gnuboard/g6/assets/155944061/fd51b2cc-d83a-4bc1-946c-2338caacdd90)

API SETTINGS.PY 파일의 내용

![image](https://github.com/gnuboard/g6/assets/155944061/b7fe6953-abdb-4078-9062-de69faae43b1)

어느쪽이 수정하면 적용되는 것인지 다소 헤갈립니다.

건의 ) env 파일에서 리프레시 토큰 만료 날짜를 세팅할 수 있었으면 좋겠습니다.
(물론settings.py) 가 있지만, 이거 수정하면 나중에 또 업데이트 해서 붙혀넣기 할 때 초기화 되니깐요 ..env 만 빼고 업데이트 할 수 있으니...

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
실제 적용되는 값은 `.env` 파일의 값을 수정해주시면 됩니다.
리프레시 토큰 만료 날짜 또한 `.env`파일에서 설정 할 수 있습니다. (일 단위)

또한 헷갈리지 않도록 ApiSettings 클래스의 주석을 추가하도록 하겠습니다.

---
참고 -  BaseSettings 설명(Chatgpt)

BaseSettings는 Pydantic 라이브러리의 일부로, 환경 변수를 사용하여 애플리케이션 설정을 관리하기 위한 편리한 방법을 제공합니다. 이는 FastAPI와 같은 애플리케이션에서 설정을 관리하고 환경 변수에서 값을 자동으로 로드하는 데 유용합니다.   

주요 특징
- 환경 변수 로드:
   BaseSettings는 설정 값을 환경 변수에서 자동으로 로드합니다. 이는 설정 값을 쉽게 구성하고 배포 환경에 맞게 조정할 수 있게 해줍니다.

- 유효성 검사 및 변환:
   Pydantic의 모델을 기반으로 하여, BaseSettings는 유효성 검사를 수행하고 설정 값을 적절한 데이터 타입으로 변환합니다.

- 기본값 설정:
   기본값을 설정할 수 있으며, 이는 환경 변수로 제공되지 않는 경우에 사용됩니다.

- 타입 힌팅:
   타입 힌팅을 통해 설정 값의 타입을 명확하게 정의할 수 있습니다.
