### ISSUE TITLE
[rest_api] 현재 접속자 JWT 미 반영건 외 건의 2건

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#561]
JWT 로 토큰 발급하여서 로그인 한 경우

현재 접속자에 포함되지 않는 것 같습니다.

관련 레코드 전체가 포함되지 않음 

예) 방문자 카운터 / 토탈 카운트 등등

일단 제가 테스트 했을 땐 위 처럼 오류가 발생하는데, 개발팀에서 한번 테스트 해보시겠습니까?

+@ 혹시 API 서버만 이용했을 경우 접속자 + 로그인 기록은 http://127.0.0.1:8000/api/v1/visit

이용해서 직접 적용해야 하는거라면...

방문자는 그렇다 치지만, 현재 접속자 자체에 출력 되지 않는건 버그가 맞는것 같습니다.

그누5 처럼 타이틀을 보여주는게 어떨까? 싶습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/8b7c18b1-8121-4fbc-80a6-952eb9f5c344)

![image](https://github.com/gnuboard/g6/assets/155944061/d326e8d8-e918-45ed-b7f1-fb50c36dfd53)

현재 접속자 로그인 상태에서 프로필 이미지가 출력되지 않습니다.

파이썬에는 해당 멤버 이미지를 가져 오게 되어있는데, api에서는 그게 불가능하니 이미지를 출력 해줘야 할 것 같습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/1f6ad3c0-9d99-49b3-9a28-4685037d0c84)

![image](https://github.com/gnuboard/g6/assets/155944061/3fcece78-e494-476e-90ab-f524d09d3c40)

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
> 그누5 처럼 타이틀을 보여주는게 어떨까? 싶습니다.

페이지 타이틀은 그누보드6의 실행 구조상,
현재 접속자 정보는 **라우터 처리 단계에서 실행**되고,
페이지 타이틀은 **뷰 단에서 선언되고 표시**되기 때문에 이를 구현하는 것이 어려울 것 같습니다.

이 외의 다른 개선사항은 반영토록 하겠습니다.

감사합니다 :)
