### ISSUE TITLE
[python] 검색어를 입력 해도 동작하지 않는 이슈 / 인기 검색어 실시간 비동기화 이슈'

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#562]
![Honeycam 2024-05-31 10-10-46](https://github.com/gnuboard/g6/assets/155944061/02b5aad7-2081-42e4-b473-ebf8da0167f5)

위 움짤 확인 시 검색이 되지 않는 이슈가 있습니다.

그래서 그런가....인기 검색어 등록도 되지 않는 것 같습니다.

수정) 

인기 검색어를 다시 확인해보니, 서버를 껐다키니 반영이 되네요...실시간 반영이 아닌 것 같습니다.

**Comment by Junanjunan** [comment]
@seiblog-nandsoft 

![image](https://github.com/gnuboard/g6/assets/73055499/23012745-ab5b-4afc-a5ee-e8606e134962)

게시판 별로 검색을 허용할지 말지 선택하는 관리자 선택사항이 있습니다.

```
관리자 페이지 > 게시판 관리 > 개별 게시판 선택 수정 >전체 검색 사용 > 사용으로 체크박스 선택
```

아마 위 설정이 되어 있지 않아서일것이라 추측하는데, 
위와 같이 설정해보시고도 검색이 안될 경우 답글 달아 주시면 자세히 살펴보겠습니다.

**Comment by seiblog-nandsoft** [comment]
@Junanjunan 이미 다 설정 되어있습니다.

움짤로 확인해보세요


![Honeycam 2024-05-31 10-29-02](https://github.com/gnuboard/g6/assets/155944061/789af6f5-49b9-40d1-8310-aaf942a43fe9)

**Comment by Junanjunan** [comment]
@seiblog-nandsoft 
fields는 
  wr_subject,
  wr_content,
  wr_subject||wr_content
중 하나를 입력하시면 됩니다.

![image](https://github.com/gnuboard/g6/assets/73055499/116f7888-6976-42f6-8539-dcac9047f7c9)

템플릿에서 위의 드랍다운 선택지에 해당합니다.

**Comment by seiblog-nandsoft** [comment]
@Junanjunan 고맙습니다!!!

**Comment by Junanjunan** [comment]
@seiblog-nandsoft 

올려주신 움짤에서 해당 검색 내용(테스트)이 갤러리가 아닌 자유게시판에 등록이 되어있고,
관리자 페이지에서 게시판 수정사항에 들어가기 전 페이지인,
전체 게시판 설정사항을 보면, 아래와 같이 free가 검색사용 체크박스가 해제 되어 있습니다.
![image](https://github.com/gnuboard/g6/assets/73055499/2d37fc71-d399-4eb3-8941-742c1aa0baba)

즉, free가 검색사용이 되어있지 않은 상태로 보여집니다.

검색 기능은 잘 동작하지만 관리자 페이지에서
게시판 검색 체크박스의 현재상태가 보여지는 것과 관련해서 오류 사항이 있는 것 같습니다.
말씀드린 부분과 겪고 계시는 이슈 사항이 일치하는지 한번 확인해 봐주시고,
관리자 단에서 보여지는 부분은 수정 반영하도록 하겠습니다.

**Comment by seiblog-nandsoft** [comment]
@Junanjunan 아 맞네요... 검색 사용 체크 하니깐 됩니다.

말씀하신 대로 관리자에서 분명 전체 검색이 허용 되어있는데 관리 페이지에서 비활성화 되어있어서 이슈가 발생했네요^^
