### ISSUE TITLE
version.txt 파일 오타

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#572]
![image](https://github.com/gnuboard/g6/assets/155944061/6c0461ef-f4de-4907-b9e5-c7e1f22b6e3b)

6.0.3 > 6.0.4 버전으로 수정해야 할 것 같습니다 하핫.

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
버전 수정이 누락되어서 반영 완료했습니다. 
제보해주셔서 감사합니다 :)
