### ISSUE TITLE
6.0.4 버전 (설치 이후) 로그인 시 발생하는 버그

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#573]
![image](https://github.com/gnuboard/g6/assets/155944061/7cae447b-eb99-4039-95b1-bdfaeae9f7f9)

제가 진행 한 순서는 다음과 같습니다.

https://sir.kr/g6_tags/48

다운로드 > 전체 압축 해제 > 기존 6.0.3 버전에 붙혀넣기 (개인적으로 수정한게 없어서 전체 복붙) > 테이블 테스트를 위해 env 파일 제거

 > mysql 로 재설치 > 설치 완료 

이후 무슨 아이디로 로그인 시도 시 위 에러 발생합니다.

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
해당 오류는 https://github.com/gnuboard/g6/commit/fcd8dc7c42181fa95c1d64f688f6a720902d473e 에서 수정되어 6.0.4 패치에 추가되었습니다.
불편을 드려 죄송합니다 (_ _
