### ISSUE TITLE
그누5에서 그누6이용 시 g5_visit PRIMARY KEY 오류

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#578]
![image](https://github.com/gnuboard/g6/assets/155944061/5743d012-b354-42e2-970b-767639e6062d)

참고로 그누보드에서 요구했던 그누5> 그누6 이용법 메뉴얼을 다 입력했지만, g5_visit 관련 내용이 누락된 것 같습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/7168a693-3933-4409-9de0-2064745825dd)

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
해당 내용은 그누보드6 매뉴얼에 반영될 예정입니다.

제보해주셔서 감사합니다 :)

![vi_id변경 내용 추가](https://github.com/gnuboard/g6/assets/57935683/fd550819-54d0-44ec-8517-515f32645609)
