### ISSUE TITLE
최근 게시물에서 파일 혹은 썸네일이 출력이 되질 않습니다.

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#579]
게시판을 통해 에디터 혹은 파일로 업로드 될 경우

파이썬의 경우 썸네일을 뿌려주어 메인에 갤러리 형태로 만들어집니다.

최근에 추가된 API에 썸네일이 없어, 갤러리 형태로 이용이 불가능합니다.

확인해보니 게시판 리스트 / 개별 게시판 리스트 등에서도 출력이 안됩니다.

**Comment by Junanjunan** [comment]
게시판과 관련해서는 API 키에서 images와 normal_files에서 파일 정보를
확인할 수 있습니다.

최근 게시물은 해당 정보 출력할 수 있도록 작업하여 추가 예정입니다.
