### ISSUE TITLE
6.0.5 업데이트 해도 로그인 URL 문제가 동일합니다.

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#592]
![image](https://github.com/gnuboard/g6/assets/155944061/4539a7a2-643d-4b75-acf7-86e6e554b7f6)

![Honeycam 2024-06-12 12-49-42](https://github.com/gnuboard/g6/assets/155944061/cfab6eb8-37c2-4c78-b055-04c1a1c71764)

ㅠ_ㅠ 살려주세요 ㅎㅎ

**Comment by seiblog-nandsoft** [comment]
@xperia-query 네 로컬이에요 ㅎㅎ

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
6.0.7 패치에서 올바르지 않은 URL일 경우 처리 방식을 변경했습니다.
- 기존 : 경고창 출력 후 로그인되지 않음
- 변경 : 메인페이지로 리다이렉트
