### ISSUE TITLE
[rest_api] 회원 가입시 회원 이미지 & 회원 아이콘 데이터 입력 누락

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#593]
![image](https://github.com/gnuboard/g6/assets/155944061/1b1d611e-f05a-4667-928c-627952785c6e)

회원 아이콘  / 회원 이미지를 받는 데이터가 누락 되어있습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/5abae1e0-b6a9-4fc5-b25a-c27477f692db)

해당 관련으로 추가 확인해본 결과... api 내에서 수정하는 api가 있지만, 이는 토큰이 발급된 회원에 한해 변경이 됩니다.

![image](https://github.com/gnuboard/g6/assets/155944061/a89d0762-44cc-41e7-a6ab-785fafc64171)

즉... 회원 가입 할 때 공식 사이트(데모사이트)에는 회원이미지/아이콘을 받는 필드가 있는 것 봐선 누락이 맞는 것으로 보입니다.

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
API는 템플릿과 조금 다르게 설계된 부분이 있으며, 회원가입 시 이미지 업로드가 분리된 것은 의도된 부분입니다.
1. 더 유연하고 확장 가능한 API 구조를 제공하려는 목적
2. 회원가입 처리와 이미지 업로드 데이터 전달 방식의 차이 (application/json, multipart/form-data)

**Comment by seiblog-nandsoft** [comment]
@KimTom89 아 의도된 부분이라면, 참고 하겠습니다. 이슈 닫겠습니다. 답변 주셔서 고맙습니다!!!
