### ISSUE TITLE
[rest_api] REFRESH_TOKEN 에 SUB 아이디 누락(?)

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#594]
![image](https://github.com/gnuboard/g6/assets/155944061/ee768277-a65b-4c80-a4b7-76e014510993)

![image](https://github.com/gnuboard/g6/assets/155944061/65aff0bf-c5ac-4263-b0a7-66e90206e0e8)

의도한 건지는 알 수 없지만,

리프레시 토큰에는 계정 정보가 누락 되어있습니다.

레디스에 리프레시 토큰 저장하려고 아이디별로 구분해서 하려고 하는데

디코드 해보니 억세스 토큰에는 있지만, 리프레시에는 누락되어있네요

버그인지 / 의도한건지 알 수 없어 글 남깁니다.

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
리프레시 토큰이 데이터베이스에 저장되어 사용되기 때문에
보안상 이유(불필요한 정보)로 payload.sub 속성에 아이디가 포함되어 있지 않았습니다.

프론트 개발에서 필요한 것으로 보아, 회원 아이디를 추가하는 방향으로 반영토록 하겠습니다.
