### ISSUE TITLE
게시글 수정시 수정대신, 신규글 생성

### ISSUE THREAD

**Issue by kjy7105** [gnuboard/g6#595]
게시글 수정시에, 기존 id값을 기준으로 내용을 수정하는 것이 아닌 신규id생성해서 새로운 게시글을 작성하는데 해당 부분에대해서 수정을 할려면 어떤부분을 봐야할까요

**Comment by Junanjunan** [comment]
테스트 상에서 말씀하신 오류재현이 되지 않는데,
어떤 방식으로 게시글을 수정하셨는지 설명을 자세히 해주실 수 있을까요?

**Comment by kjy7105** [comment]
![Screenshot from 2024-06-13 10-49-38](https://github.com/gnuboard/g6/assets/85718425/0d731c98-277d-47f1-94a7-81714de9788e)
![Screenshot from 2024-06-13 10-49-55](https://github.com/gnuboard/g6/assets/85718425/8db6142a-adb8-47ed-964f-73108f4df854)
![Screenshot from 2024-06-13 10-50-11](https://github.com/gnuboard/g6/assets/85718425/18225f3b-1844-45d9-8028-2eac8915640f)

부트스트랩 테마에서 해보는중이며

현재 사진처럼 게시글을 생성해서 id값이 9인 게시글을 수정하려고 하였을때 수정하는 창까지는 정상적으로, 9를 기준으로 내용도 불러오지만,

내용 수정후에 완료를 클릭하면 새로운게시글이 생성됩니다.

**Comment by Junanjunan** [comment]
부트스트랩 테마 템플릿에서 wr_id 파라미터가 조건적으로 붙는 부분이 생략되어 있어서 발생한 문제입니다.
수정해서 다음 버전에 반영하도록 하겠습니다.
