### ISSUE TITLE
[rest_api][5차 수정] 회원 가입 시 발생되는 이슈 및 건의

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#598]
죄송합니다 사진에 본의 아니게 테스트 용도로 가입한다고 욕설이 있어요 ㅠ_ㅠ;;

쨋든 회원 가입 시 비속어가 필터가 되지 않고 그냥 회원 가입이 통과 됩니다.

![image](https://github.com/gnuboard/g6/assets/155944061/d305415f-852a-4653-85d9-9c57af6f3f40)

PS. 질문! API 사용 시 캡차는 별도로 사용해야 하는게 맞는거죠 ?

[추가]

![image](https://github.com/gnuboard/g6/assets/155944061/25e8958e-fc4f-4af9-ae21-e3f1f9cbf3c9)

관리자가 설정한 아이디 / 닉네임을 사용할 수 없게 필터가 되는 거 봐서는 버그가 확실한 것 같습니다.

단어로 필터가 되면, 그 단어가 포함되었다면 에러가 발생하는 게 좋을 것 같다는 건의를 드리고자 합니다.

사유는 다음과 같습니다.

administrator  필터링 됩니다.

그렇지만, 교모하게 바꾼건 통과가 됩니다.

예) administrator1 / Administrator / adminiStrator  이렇게 하나라도 대문자가 있으면 그냥 통과 됩니다.

[2차수정]

위에 언급된 부분은 프론트로 해결은 했지만, 보안을 위해서, 백엔드에도 적용을..ㅠㅠ

또한, 비밀번호도 자릿수 제한 없이 가입이 되네요

예를 들어 한자리 입력해도 가입이 됨...

![image](https://github.com/gnuboard/g6/assets/155944061/cde16ceb-f1f2-4289-a56d-19033300e53b)

[3차수정]

회원 가입시 추천인을 자기 자신을 등록해도 정상적으로 등록되고 포인트도 적립 됩니다.

![image](https://github.com/gnuboard/g6/assets/155944061/6150e176-b86c-4d8b-b9a1-e719135484b9)

![image](https://github.com/gnuboard/g6/assets/155944061/0c8588eb-1f1b-407a-b6ec-76e683f529b3)

또한 이메일 인증을 하지 않은 경우에도, 추천인 포인트 적립이 됩니다.

**이메일 인증이 정상적으로 완료 된 경우 or 소셜 회원가입(추후)이 완료된 경우에만 추천인 포인트 적립이 되는게 버그 방지에 좋을 듯 합니다.

예) 일부러 추천인 포인트 얻기 위해 허위 아이디로 무조건 회원 가입** 

오늘은 회원가입 페이지를 완성한다고 이것 저것 테스트 하는 과정에 나온 이슈들입니다. 

[4차수정]

이메일을 잘못 입력하여 회원 가입 시 수정하는 API 가 별도로 없습니다.

기존 그누보드5에서는 이메일 잘못 인증시 아래 처럼 볼 수 있습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/62b889f0-47e6-420d-859e-edd29b397852)

![image](https://github.com/gnuboard/g6/assets/155944061/babe8116-7747-4542-b8b4-f7a474c68897)

그렇지만, 그누6 rest_api 에서는 

![image](https://github.com/gnuboard/g6/assets/155944061/dca6296d-27dc-4350-a216-e82bc41c2344)

인증만 받으라고 안내가 될뿐 실제 변경할 수 있는 api가 없습니다.

(비밀번호 재설정 / 재설정 메일은 있습니다만 이메일 변경 api가 없어 이슈로 남깁니다.)

![image](https://github.com/gnuboard/g6/assets/155944061/c8579eb4-08ad-4396-a5a8-8d60689a27d4)

[5차수정] 

회원 정보에 대한 여분 필드 누락이 다음과 같습니다. (회원 가입 시 여분 필드 1~10번까지 데이터를 입력 받음)

1. 현재 로그인 회원 정보 조회 

2. 회원 정보 조회

**3. 회원 정보 수정**

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
올려주신 회원가입 관련 이슈 및 건의사항 적용 완료했으며, 
캡챠를 검증할 수 있는 API도 추가했습니다. 

![캡챠](https://github.com/gnuboard/g6/assets/57935683/b75b0a34-e4bc-44f0-a2d1-8248ded71593)

감사합니다.

**Comment by seiblog-nandsoft** [comment]
@KimTom89 고맙습니다. 사...ㅅ.ㅏ..사..랑합니다 ㅎㅎㅎㅎ
