### ISSUE TITLE
그누보드6.0.7 버전 설치 시 500에러 반환

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#602]
순서는 다음과 같습니다.

https://sir.kr/g6_tags/52

다운로드 한 뒤 설치 할 거 하고 실행하면 500에러가 반환됩니다.

(기존이 아니라 완전히 새로 받았다 가정하에 500에러)

테스트로 완전히 아무것도 건드리지 않고 실행만 했는데도 500에러가 뜹니다.

추가) 2024-06-19-10:08 

git clone 을 해서 동작해도 500에러 발생됩니다

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
이슈 올려주신 후, 저희 측에서 테스트를 진행했는데 정상적으로 설치됨을 확인했습니다.

번거로우시겠지만, 설치 환경에 대해 코멘트 달아주신다면 에러를 해결하는데 도움이 될 것 같습니다.
- 설치 환경
- 서버 로그 (uvicorn)
- 데이터베이스 등..

감사합니다 :)

**Comment by seiblog-nandsoft** [comment]
@KimTom89 

추가입니다

1. 윈도우
2. 서버로그 없습니다. (영상 확인)
3. 설치 자체가 안됩니다. 그냥 로컬 자체가 에러남 아래 영상 확인해주세요
업로드 용량이 10메가까지 밖에 되지 않아 분할 하였음을 참고하시길 바랍니다.


https://github.com/gnuboard/g6/assets/155944061/a4da29d6-26fd-452a-ae3e-7c8f04c993fa


https://github.com/gnuboard/g6/assets/155944061/c136d545-03a9-4ade-b447-79d47c9f2a78


https://github.com/gnuboard/g6/assets/155944061/330548df-13cf-40ad-9f49-0cd2b395d6a2


https://github.com/gnuboard/g6/assets/155944061/88345d6b-dbd7-4add-96bf-4d954e7a8e15

**Comment by seiblog-nandsoft** [comment]
@KimTom89 해결 완료 하였습니다.
