### ISSUE TITLE
토큰 비밀키 미적용 이슈...

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#607]
6.0.7 버전에서

env 파일 내 

ACCESS_TOKEN_SECRET_KEY
REFRESH_TOKEN_SECRET_KEY

코드가 동작하지 않습니다.

근데 이게 100% 확률도 동작하는게 아니라 간헐적으로 동작합니다.
현재는 또 env에서 세팅한 시크릿 코드가 정상적으로 동작합니다.ㅠ_ㅠ

![Honeycam 2024-06-20 13-21-03](https://github.com/gnuboard/g6/assets/155944061/2e702930-8ad7-47fd-a421-b7abf94b312a)

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
혹시 `.env` 파일을 수정하신 이후 서버가 재시작되었나요? 올려주신 이미지로는 재시작된 로그를 확인할 수가 없네요..
`.env` 파일을 수정하시면 서버가 재시작되어야 정상적으로 반영됩니다.

**Comment by seiblog-nandsoft** [comment]
@KimTom89 테스트를 위해 저렇게 해둔 것이구요

처음부터 시크릿키는 입력된 상태이고 기존에 "잘 사용하다가" 갑자기 시크릿 에러 나길래 ? 뭐지 하고 settings.py 코드 넣으니 동작하더라구요

.... 그러니깐 임의로 수정한건 아니에요 위에 움짤은 테스틀 위해 .... ㅠ

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
다방면으로 테스트를 진행했지만, 비밀키가 적용된 토큰이 정상적으로 생성되어서 해당 오류를 재현할 수 없었습니다.

임시로 `api/settings.py`  최하단에 아래 코드를 추가하셔서 비밀키가 제대로 선언/적용되는지 확인부탁드립니다.
``` python 
print("ACCESS_TOKEN_SECRET_KEY : ", api_settings.ACCESS_TOKEN_SECRET_KEY)
print("REFRESH_TOKEN_SECRET_KEY : ", api_settings.REFRESH_TOKEN_SECRET_KEY)
```

동일한 문제가 계속 발생 시, 오류가 발생한 토큰을 함께 보내주시면 다시 한번 파악해보도록 하겠습니다.

감사합니다.
