### ISSUE TITLE
쪽지 보내기 포인트 버그 및 추가 이슈

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#609]
1. 메세지가 다소 어색합니다.

테스트> 보유 포인트 110  / 메세지 보내기 아이디 2명 입력 / 보내기 시도

![image](https://github.com/gnuboard/g6/assets/155944061/809eb7d0-2674-4fd4-9a9b-12e61dae875e)

그럼 200포인트가 소모되므로 90포인트가 부족합니다.

하지만, 실제 출력되는 텍스트가 다소 어색합니다.

![image](https://github.com/gnuboard/g6/assets/155944061/cc9e3a4e-077c-473e-a244-934053469530)

api의 경우도 메세지 출력이 다소 어색합니다.

![image](https://github.com/gnuboard/g6/assets/155944061/a300e90b-d8bd-4f2c-90a3-28a712c5dac7)

2. 메세지 전송버그입니다.

쪽지 보낼 시 100포인트임에도 여러명 보낼 시 해당 인원수 만큼 포인트가 차감됩니다.

![image](https://github.com/gnuboard/g6/assets/155944061/db9d70a4-7cbe-4ae3-9761-8ba16a6568dc)

4명에게 보내면 400포인트씩 1600포인트가 차감됩니다.

파이썬으로 보내나 / rest_api 로 보내나 둘다 동일 증상입니다.

![image](https://github.com/gnuboard/g6/assets/155944061/03c1aaba-e23f-43a1-b804-7162af3a6f36)

3. 의도한 건지는 알 수 없으나, 이메일 인증 받지 않은 회원에게도 쪽지가 보내지는데 이건 원래 그런건지 몰라서 "질문"드리는겁니다.

4. 받은 쪽지 + 보낸 쪽지 > 사용자 클릭 > 사이드 뷰 > 쪽지 보내기를 할 시 해당 사용자 아이디가 미리 입력 되지 않는 이슈

해당 사용자에 대한 쪽지 보내기 기능인데, 아이디가 입력되지 않으면 그건 이상한 것 같습니다. (파이썬입니다.)

![image](https://github.com/gnuboard/g6/assets/155944061/eec14673-ca15-4a21-a233-307d9940d695)

아이디가 입력 되어있지만, input 에 입력이 안되는 것 같습니다.

일단 확인한 건 여기까지이며, 쪽지 관련 발견하면 수정 하겠으며, 다른 이슈가 있다면 새로운 이슈로 남기겠습니다.

**Comment by Junanjunan** [comment]
3. 의도한 건지는 알 수 없으나, 이메일 인증 받지 않은 회원에게도 쪽지가 보내지는데 이건 원래 그런건지 몰라서 "질문"드리는겁니다.
  -> 쪽지 수신 여부는 이메일 인증이 아닌 정보 공개 여부로 선택할 수 있습니다.

나머지 부분은 수정하여 다음 패치에 반영되도록 하겠습니다.

**Comment by seiblog-nandsoft** [comment]
@Junanjunan 메일이 성공적으로 발송되었다고는 안내 되나 실제로 발송이 안됩니다.

![image](https://github.com/gnuboard/g6/assets/155944061/efd24e29-b038-46df-9e47-398a15744d8d)

혹시라도 메일 설정 말씀하실까봐 미리 말씀드릴께요

![image](https://github.com/gnuboard/g6/assets/155944061/73a27fa7-9b97-444b-8e4f-94468c00b185)

위는 1:1 질문 입니다. 똑같이 메일 보냈다고 뜨고

메일도 잘 옵니다.

![image](https://github.com/gnuboard/g6/assets/155944061/68d8c975-acb8-4fa5-bf7b-183223cdf610)
