### ISSUE TITLE
관리자 화면 특정 메뉴 500에러 발생 이슈 및 요청 건의

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#611]
![image](https://github.com/gnuboard/g6/assets/155944061/f8bfecec-7ea7-4f5c-a506-47585ed36b3c)

1:1 문의 설정 > 확인 > 500에러가 출력됩니다.

+

그누5에 있던 관리자 SMS 관리 메뉴는 그누6에 존재하지 않는 것 같던데 아직 미구현 상태인 것 같지만,

어쨋든 요청 드립니다.

**Comment by Junanjunan** [comment]
1:1 문의 설정 > 확인 > 500 에러로 올려주신 부분에 대한 에러 재현이 되지 않습니다.
에러 로그를 참고하셔서 수정 작업 중에 설정이 변한 것인지 확인해보시기 바랍니다.
배포한 버전과 코드 변화를 주지 않았음에도 에러 발생시, 에러 로그를 함께 첨부해주시기 바랍니다.

**Comment by seiblog-nandsoft** [comment]
@Junanjunan 

기존 데이터만 덮어씌운 상태입니다. 코드 수정은 하지 않은 상태입니다.

(그누5 데이터로 테스트 하다보니, 기존 그누5의 데이터베이스 상태임을 참조해주시길 바랍니다.)

에러코든튼 다음과 같습니다.

![image](https://github.com/gnuboard/g6/assets/155944061/48f7c11e-404d-4cb0-8688-12843cda6332)
