### ISSUE TITLE
[건의] 업데이트 패치 파일만 업로드 해주실수 없나요?ㅠ

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#614]
https://sir.kr/g5_pds/7205

그누5의 경우는 전체 파일 + 패치 파일을 별도로 업로드 되어

패치 부분만 수정할 수 있게끔 되어있는데

그누6에서도 그렇게 지원해주실 수는 없으신지요 ?

**Comment by KimTom89** [comment]
다음 패치버전부터는 변경된 파일의 압축본을 추가적으로 업로드하겠습니다.

감사합니다 :)
