### ISSUE TITLE
[rest_api] 정확한 판단 및 내용을 확인할 수 없어 이슈 등록

### ISSUE THREAD

**Issue by seiblog-nandsoft** [gnuboard/g6#615]
![Honeycam 2024-06-28 16-10-17](https://github.com/gnuboard/g6/assets/155944061/5e4cff38-17cb-4bce-9f75-137c4980d672)

api 의 경우 현재 접속자가 보여지는 원리를 잘 모르겠습니다.

메인 + 로그인이 되어있음에도 로그인 정보가 출력되지 않고,

단순히 api 호출에 관련된 내용인가? 싶어 ...

![image](https://github.com/gnuboard/g6/assets/155944061/a8f300ce-feea-4f6f-a2a9-de4382ab9145)

이렇게 호출해도 동일 증상이 있습니다.

로컬이기 때문에 현재 로그인 사용자 + 접속 사용자는 당연히 저뿐인데...움짤에 보시면  아시겠지만, 분명히 로그인을 했습니다.

정확하게 어떤 원리인지 몰라 이슈로 남깁니다.

[추가]

실제 서버에 등록 이후 휴대폰(와이파이 아님) + 인터넷으로 접속해도 2명이 되지 않고 1명으로 출력

그리고 로그인 시 로그인 회원이 나오지 않고 빈값으로 리턴됩니다.

**Comment by KimTom89** [comment]
@seiblog-nandsoft 
기본적으로 현재 사용자는 현재 접속된 IP를 기준으로 고유한 사용자라고 판단하고 있으며
템플릿과 API에서 로그인 사용자를 가져오는 방법이 달라서 발생한 상황인 것으로 확인됩니다.

#### 1. 템플릿
- **세션**을 기반으로 현재 접속정보를 출력/갱신합니다.
#### 2. API
- Header로 전송된 **Token**을 기반으로 현재 접속정보를 출력/갱신합니다.

**Comment by seiblog-nandsoft** [comment]
@KimTom89 답변 감사합니다. 조금 더 테스트 해보겠습니다.
